### ISSUE TITLE
Verify Rule-Type-Switching Problem isn't a problem

### ISSUE THREAD

**Issue by bsamuel** [ensemble-engine/ensemble#2] opened 2016-07-22 23:38 UTC
Before Pulling Aaron's recent amazing authoring tool changes, I realized that I had some changes to the authoring tool committed locally that I hadn't pushed to the repo yet. One of them included the following commit message:

"Fixed a bug in the authoring tool that was changing the 'type' of rule files from trigger to volition if the editor switched back and forth in a single editing session."

To ease the merging process, I stashed my changes and simply did a pull. It's possible that in Aaron's refactoring he addressed the issue that I fixed in my local commit. But it should be verified that this is the case. If it isn't, a new issue to fix it should be created.

**Comment by aaronareed** [comment] 2017-07-30 06:42
Duplicate of #13

**Closed by aaronareed** 2017-07-30 06:42 UTC
Labels: Tool
