### ISSUE TITLE
Build Windows version of tool with updated NW.js

### ISSUE THREAD

**Issue by meldckn** [ensemble-engine/ensemble#99] opened 2019-11-28 00:16 UTC
Trying to build the Windows version of the tool from the `build-console-for-windows.py` script is broken as @mkremins and I expected with the tool changes from https://github.com/ensemble-engine/ensemble/commit/e1d6bca349d3cafb47bb7843fc3c90bec82ac0c7 (the app errors out with complaints about the new JavaScript features we used, e.g., `=>` and promises). 

I tried editing the Python script to reference a newly downloaded NW.js directory, `nwjs-sdk-v0.42.5-win-x64`, and removed outdated references to `nw.pak`. But it obviously still wasn't following the [new NW.js packaging steps](http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/) because running the exe generated from that logged errors like: `Failed to load NW DLL from [tool path]\nw.dll: The specified module could not be found. (0x7E)`

When I tried to follow the packaging steps by hand from the NW.js website linked above (Package Option 1), the exe/app wouldn't even open. I was probably doing something wrong but I can't figure out what. 

I also still want to have a single build process for Mac and Windows because this seems like a silly and tedious discrepancy to have (#95). I think overlong paths of stuff in our `node_modules` might be the culprit. But I investigated briefly and couldn't find any path names >256 characters (the Windows limit). But they could be buried in nested folders that I missed. @mkremins, do you know what all those node modules are used for and if we can get rid of them? FYI, the long path thing is also mentioned on the NW.js website as a known problem: 

> The length of path used in your app may exceed the maximum length (260 characters) on Windows. That will cause various build failures. This usually happens during installing dependencies with `npm install` using older version of NPM (<3.0). Please build your app in the root directory, like `C:\build\`, to avoid this issue as much as possible.

But I just checked the NPM version and we're past 3.0, and I tried building at root but no difference in behavior. 

It's also discussed at https://github.com/nwjs-community/nw-builder/issues/107

Haven't tried flattening modules or anything yet (as mentioned in that thread), because I didn't see obvious culprit modules. 

Anyway, I'm not going to continue on this right now because I'm getting nowhere.

**Comment by mkremins** [comment] 2019-11-28 00:53
I'm not sure what's going on here, but I just took a first pass (in commit https://github.com/ensemble-engine/ensemble/commit/a4fbbdd638a2f236577ccbdfd07c71b9a8ad7d90) at cleaning up the Gruntfile and then removing unused dependencies from `package.json`. This did seemingly succeed at stripping out a lot of dependencies, so maybe it's worth another try now?

**Comment by mkremins** [comment] 2019-11-28 01:08
The other weird thing I've just realized is that I don't think we even use any `node_modules` dependencies within the authoring tool – so maybe we don't even need to copy the `node_modules` folder into the authoring tool package at all! All of our current `node_modules` dependencies are `devDependencies`, which means they're used in the build process but not in any of the software we're actually releasing.

**Comment by mkremins** [comment] 2019-11-29 13:56
Okay so I had a fairly out-there idea: what if we just switched over to Electron instead of continuing to fight with nw.js? And then I started trying to actually implement it and found that the Electron documentation is much nicer and more complete than the nw.js docs, and the multiplatform support seems much more thoroughly thought out, and...

End result: [the `electron` branch](https://github.com/ensemble-engine/ensemble/tree/electron) represents an alternate reality in which we're using Electron to distribute the authoring tool instead of nw.js.

The initial setup took some doing, but with Electron, I was eventually able to cajole my computer into producing an executable Windows version of the authoring tool alongside the Mac version (which I've confirmed is working, at least as far as loading the `sampleGame` domain and running `next` in the console). I have no way of testing the Windows builds I'm producing, so I have no idea whether they actually do anything at all, but we could try either of the following ways to test them:

1. Pull the `electron` branch down on a Windows machine and run the build process (still just `grunt build`) from there, then run the resulting executables locally.
2. Move the alleged Windows executables I've got on my machine onto a Windows machine and try running them there.

Here's the steps I ended up having to take to produce alleged Windows builds on my MacBook:
```bash
# uninstall any version of Wine you've already got installed
brew cask uninstall wine-stable
brew uninstall wine
# then ensure you don't have any version of
# /usr/local/bin/wine or /usr/local/bin/wine64 installed

# install a version of Wine that supports x64
brew install homebrew/cask/wine-stable

# clean out any lingering Wine config files you might have in your homedir
rm -r ~/.wine

# run the build process
grunt build
# it's ok to say "cancel" to all the Wine prompts about installing Mono/Gecko
```

I think Electron might also give us a Linux build for free (potentially resolving #81), so that's neat? As with the Windows builds, I'm already producing something that _claims_ to be a Linux executable, so now it's just a matter of testing whether or not these executables actually work.

**Comment by mkremins** [comment] 2019-11-29 22:43
Tested the Windows builds from my machine on Isaac's laptop and they actually worked! (Or at least the x64 version did.) Was able to load the `sampleGame/data` folder and run `next` in the console, with everything apparently working as intended.

**Comment by meldckn** [comment] 2019-11-30 23:26
That's so so rad, thanks for doing that!! I'm in favor of changing to Electron and merging your branch into master! We should also make a new release with the working builds, and edit the [wiki page on developing the authoring tool](https://github.com/ensemble-engine/ensemble/wiki/Developing-the-Authoring-Tool). And we can test the Linux build when we're next up on campus.

**Comment by mkremins** [comment] 2019-12-01 00:40
Awesome! Went ahead and merged the changes into master, then cut a [new release (v1.1.0)](https://github.com/ensemble-engine/ensemble/releases/tag/v1.1.0).

**Closed by mkremins** 2019-12-01 00:40 UTC
Labels: ensemble tool
